from Tutel.InterpreterModuler.Turtle.Color import Color
from Tutel.InterpreterModuler.Turtle.Position import Position


class GuiInterface:
    @classmethod
    def set_color(cls, turtle_id: int, color: Color) -> bool: ...
    @classmethod
    def set_position(cls, turtle_id: int, position: Position) -> bool: ...
    @classmethod
    def set_orientation(cls, turtle_id: int, orientation: int) -> bool: ...
    @classmethod
    def add_turtle(cls, turtle_id: int, color: Color, position: Position, orientation: int) -> bool: ...
