from tutel.InterpreterModule.Turtle.Color import Color
from tutel.InterpreterModule.Turtle.Position import Position


class GuiInterface:
    def set_color(self, turtle_id: int, color: Color) -> bool: ...
    def set_position(self, turtle_id: int, position: Position) -> bool: ...
    def set_orientation(self, turtle_id: int, orientation: int) -> bool: ...
    def add_turtle(self, turtle_id: int, color: Color, position: Position, orientation: int) -> bool: ...
