from Tutel.debugger.RequestsHandler.DataStructures import DebuggerRequest, DebuggerResponse, DebuggerEvent


class RequestsHandlerInterface:
    def receive_request(self) -> DebuggerRequest: ...
    def send_response(self, response: DebuggerResponse | DebuggerEvent): ...
    @staticmethod
    def stop(): ...
