from Tutel.core.InterpreterModule.Turtle.Color import Color
from Tutel.core.InterpreterModule.Turtle.Orientation import Orientation
from Tutel.core.InterpreterModule.Turtle.Position import Position


class GuiInterface:
    def set_color(self, turtle_id: int, color: Color) -> bool: ...
    def set_position(self, turtle_id: int, position: Position) -> bool: ...
    def set_orientation(self, turtle_id: int, orientation: Orientation) -> bool: ...
    def add_turtle(self, turtle) -> bool: ...
    def go_forward(self, turtle_id: int, position: Position) -> bool: ...
    def pen_up(self, turtle_id: int) -> bool: ...
    def pen_down(self, turtle_id: int) -> bool: ...
